<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>{{ __('Revenue Analytics Export') }}</title>
<style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 12px; color: #1a1a2e; background: #fff; padding: 24px; }
    .header { display: flex; align-items: center; justify-content: space-between; border-bottom: 2px solid #0d9488; padding-bottom: 16px; margin-bottom: 24px; }
    .brand { font-size: 22px; font-weight: 700; color: #0d9488; letter-spacing: -0.5px; }
    .brand span { color: #6366f1; }
    .meta { text-align: right; font-size: 11px; color: #6b7280; line-height: 1.6; }
    .title { font-size: 18px; font-weight: 700; color: #111827; margin-bottom: 4px; }
    .subtitle { font-size: 12px; color: #6b7280; margin-bottom: 20px; }
    .summary { display: flex; gap: 12px; margin-bottom: 24px; }
    .summary-card { flex: 1; background: #f0fdfa; border: 1px solid #99f6e4; border-radius: 8px; padding: 12px 16px; }
    .summary-card .label { font-size: 10px; font-weight: 600; color: #0f766e; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 4px; }
    .summary-card .value { font-size: 16px; font-weight: 700; color: #134e4a; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
    thead tr { background: #0d9488; color: #fff; }
    thead th { padding: 10px 12px; text-align: left; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.4px; }
    tbody tr:nth-child(even) { background: #f0fdfa; }
    tbody tr:hover { background: #ccfbf1; }
    tbody td { padding: 8px 12px; border-bottom: 1px solid #e5e7eb; }
    .text-right { text-align: right; }
    .empty { text-align: center; padding: 40px; color: #9ca3af; font-style: italic; }
    .footer { border-top: 1px solid #e5e7eb; padding-top: 12px; font-size: 10px; color: #9ca3af; text-align: center; }
    @media print { body { padding: 0; } }
</style>
</head>
<body>

{{-- Header: BR-458 — DancyMeals logo, generated date, user name --}}
<div class="header">
    <div class="brand">Dancy<span>Meals</span></div>
    <div class="meta">
        <div><strong>{{ __('Generated by') }}:</strong> {{ $userName }}</div>
        <div><strong>{{ __('Generated on') }}:</strong> {{ $generatedAt->format('M j, Y H:i') }}</div>
        <div><strong>{{ __('Cook') }}:</strong> {{ $cookName }}</div>
    </div>
</div>

<div class="title">{{ __('Revenue Analytics Report') }}</div>
<div class="subtitle">
    {{ __('Period') }}: {{ $rangeStart->format('M j, Y') }} – {{ $rangeEnd->format('M j, Y') }}
    &nbsp;&middot;&nbsp; {{ __('Completed orders only') }}
</div>

@if($hasData)
    {{-- Summary cards --}}
    <div class="summary">
        <div class="summary-card">
            <div class="label">{{ __('Total Revenue') }}</div>
            <div class="value">{{ \App\Services\AnalyticsExportService::formatXAF($totalRevenue) }}</div>
        </div>
        <div class="summary-card">
            <div class="label">{{ __('Total Orders') }}</div>
            <div class="value">{{ number_format($totalOrders) }}</div>
        </div>
        <div class="summary-card">
            <div class="label">{{ __('Avg. per Order') }}</div>
            <div class="value">{{ $totalOrders > 0 ? \App\Services\AnalyticsExportService::formatXAF((int)round($totalRevenue / $totalOrders)) : '—' }}</div>
        </div>
    </div>

    {{-- Data table --}}
    <table>
        <thead>
            <tr>
                <th>{{ __('Date') }}</th>
                <th class="text-right">{{ __('Revenue (XAF)') }}</th>
                <th class="text-right">{{ __('Order Count') }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($rows as $row)
                <tr>
                    <td>{{ $row['date'] }}</td>
                    <td class="text-right">{{ number_format($row['revenue']) }}</td>
                    <td class="text-right">{{ number_format($row['order_count']) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
@else
    <div class="empty">{{ __('No data available for the selected period') }}</div>
@endif

<div class="footer">
    {{ __('DancyMeals — Analytics Export') }} &middot; {{ $generatedAt->format('Y') }}
</div>

</body>
</html>
