<?php

namespace App\Mail;

use App\Models\User;

/**
 * DancyMeals-branded password reset notification (N-022).
 *
 * Extends BaseMailableNotification for consistent branding, locale-aware
 * content, and queued delivery via the high-priority emails queue (BR-121).
 *
 * The reset URL is generated by the controller and passed in as a parameter.
 * Token expires after 60 minutes (BR-066, configured in config/auth.php).
 */
class PasswordResetMail extends BaseMailableNotification
{
    /**
     * The password reset URL.
     */
    protected string $resetUrl;

    public function __construct(
        protected User $user,
        string $resetUrl,
    ) {
        $this->resetUrl = $resetUrl;
        $this->forRecipient($user);
        $this->forTenant(tenant());
        $this->initializeMailable();
    }

    /**
     * Get the localized email subject line (N-022).
     */
    protected function getSubjectLine(): string
    {
        return $this->trans('Reset your DancyMeals password');
    }

    /**
     * Get the blade view name for the email content.
     */
    protected function getEmailView(): string
    {
        return 'emails.password-reset';
    }

    /**
     * Get the data to pass to the email view.
     *
     * @return array<string, mixed>
     */
    protected function getEmailData(): array
    {
        return [
            'userName' => $this->user->name,
            'resetUrl' => $this->resetUrl,
            'expirationMinutes' => config('auth.passwords.users.expire', 60),
        ];
    }

    /**
     * Mark as critical email for high-priority queue routing (BR-121).
     */
    protected function getEmailType(): string
    {
        return 'password_reset';
    }
}
